name: Flutter Desktop Deployment

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install project dependencies
        run: flutter pub get

      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Windows
        run: flutter build windows --release

      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: train_map-${{github.ref_name}}-windows.zip
          directory: build/windows/x64/runner/Release

      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: build/windows/x64/runner/Release/train_map-${{github.ref_name}}-windows.zip
